pub const NUM_ZYRTHIDS: usize = 1;
pub const NUM_FERNWORMS: usize = 10;
pub const MAX_BERRIES: u64 = 10;

pub const BERRY_FULLNESS_GAIN: f32 = 40.0;
pub const FERNWORM_FULLNESS_GAIN: f32 = 80.0;

pub const BERRY_RENDER_HEIGHT: f32 = 16.0;
pub const BERRY_RENDER_WIDTH: f32 = 16.0;

pub const FERNWORM_SPRITE_HEIGHT: u32 = 16;
pub const FERNWORM_SPRITE_WIDTH: u32 = 7;
pub const FERNWORM_SCALE_FACTOR: f32 = 4.0;
pub const FERNWORM_RENDER_HEIGHT: f32 = (FERNWORM_SPRITE_HEIGHT as f32) * FERNWORM_SCALE_FACTOR;
pub const FERNWORM_RENDER_WIDTH: f32 = (FERNWORM_SPRITE_WIDTH as f32) * FERNWORM_SCALE_FACTOR;

pub const ZYRTHID_SPRITE_HEIGHT: u32 = 25;
pub const ZYRTHID_SPRITE_WIDTH: u32 = 11;
pub const ZYRTHID_SCALE_FACTOR: f32 = 4.0;
pub const ZYRTHID_RENDER_HEIGHT: f32 = (ZYRTHID_SPRITE_HEIGHT as f32) * ZYRTHID_SCALE_FACTOR;
pub const ZYRTHID_RENDER_WIDTH: f32 = (ZYRTHID_SPRITE_WIDTH as f32) * ZYRTHID_SCALE_FACTOR;

pub const SCREEN_WIDTH: f32 = 1920.0;
pub const SCREEN_HEIGHT: f32 = 1080.0;
pub const PLAYABLE_AREA_X0: f32 = -(SCREEN_WIDTH / 2.0 - 350.0);
pub const PLAYABLE_AREA_X1: f32 = SCREEN_WIDTH / 2.0 - 350.0;
pub const PLAYABLE_AREA_Y0: f32 = -(SCREEN_HEIGHT / 2.0 - 200.0);
pub const PLAYABLE_AREA_Y1: f32 = SCREEN_HEIGHT / 2.0 - 200.0;
